In [4]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import math
sns.set(style="darkgrid")

df = pd.read_csv('2020-XTern-DS.csv')
df.columns = ['id', 'lat', 'long', 'food', 'avg_cost', 'min_order', 'rate', 'votes', 'review', 'time']
df.time = df.time.str.extract("(\d*\.?\d+)", expand=True)
df.review = df.review.str.extract("(\d*\.?\d+)", expand=True)
df.votes = df.votes.str.extract("(\d*\.?\d+)", expand=True)
df.rate = df.rate.str.extract("(\d*\.?\d+)", expand=True)
df.min_order = df.min_order.str.extract("(\d*\.?\d+)", expand=True)
df.avg_cost = df.avg_cost.str.extract("(\d*\.?\d+)", expand=True)
df.time = df.time.apply(pd.to_numeric)
df.review = df.review.apply(pd.to_numeric)
df.votes = df.votes.apply(pd.to_numeric)
df.rate = df.rate.apply(pd.to_numeric)
df.min_order = df.min_order.apply(pd.to_numeric)
df.avg_cost = df.avg_cost.apply(pd.to_numeric)
df

,id,lat,long,food,avg_cost,min_order,rate,votes,review,time
0,ID_6321,39.262605,-85.837372,"Fast Food, Rolls, Burger, Salad, Wraps",20.0,50.0,3.5,12.0,4.0,30
1,ID_2882,39.775933,-85.740581,"Ice Cream, Desserts",10.0,50.0,3.5,11.0,4.0,30
2,ID_1595,39.253436,-85.123779,"Italian, Street Food, Fast Food",15.0,50.0,3.6,99.0,30.0,65
3,ID_5929,39.029841,-85.332050,"Mughlai, North Indian, Chinese",25.0,99.0,3.7,176.0,95.0,30
4,ID_6123,39.882284,-85.517407,"Cafe, Beverages",20.0,99.0,3.2,521.0,235.0,65
...,...,...,...,...,...,...,...,...,...,...
2014,ID_4366,39.624978,-85.189212,"North Indian, Pizza, Burger, Continental",40.0,0.0,NaN,NaN,NaN,30
2015,ID_319,39.133719,-85.503020,"Awadhi, Bihari",40.0,99.0,4.1,118.0,91.0,30
2016,ID_3104,39.662987,-85.950894,"Fast Food, Beverages",10.0,50.0,NaN,NaN,NaN,30
2017,ID_4396,39.301765,-85.662768,"Kebab, Fast Food",10.0,50.0,NaN,NaN,NaN,30
2018,ID_8403,39.460944,-85.484355,"Desserts, Beverages",150.0,50.0,4.1,271.0,172.0,45

In [2]:
foodToVotes = {}
for ind in df.index: 
    if(math.isnan(df.votes[ind])) :
        continue;
    else :
        foodTypes = df.food[ind].split(", ")
        for food in foodTypes :
            if food in foodToVotes :
                foodToVotes[food] += df.votes[ind]
            else :
                foodToVotes[food] = df.votes[ind]
            
votesToFood = dict([(value, key) for key, value in foodToVotes.items()]) 
sortDict = sorted(votesToFood, reverse=True)
print("The top 5 resturant types by user voting are:\n")
print("1: ", votesToFood[sortDict[0]] + " with " + str(sortDict[0]) + " votes")
print("2: ", votesToFood[sortDict[1]] + " with " + str(sortDict[1]) + " votes")
print("3: ", votesToFood[sortDict[2]] + " with " + str(sortDict[2]) + " votes")
print("4: ", votesToFood[sortDict[3]] + " with " + str(sortDict[3]) + " votes")
print("5: ", votesToFood[sortDict[4]] + " with " + str(sortDict[4]) + " votes")
print("\n\n")

sortDict = sorted(votesToFood)
print("The worst 5 resturant types by user voting are:\n")
print("1: ", votesToFood[sortDict[0]] + " with " + str(sortDict[0]) + " votes")
print("2: ", votesToFood[sortDict[1]] + " with " + str(sortDict[1]) + " votes")
print("3: ", votesToFood[sortDict[2]] + " with " + str(sortDict[2]) + " votes")
print("4: ", votesToFood[sortDict[3]] + " with " + str(sortDict[3]) + " votes")
print("5: ", votesToFood[sortDict[4]] + " with " + str(sortDict[4]) + " votes")

The top 5 resturant types by user voting are:

1:  North Indian with 188064.0 votes
2:  Chinese with 142351.0 votes
3:  Fast Food with 92807.0 votes
4:  Italian with 82505.0 votes
5:  Continental with 62181.0 votes



The worst 5 resturant types by user voting are:

1:  Konkan with 6.0 votes
2:  Bangladeshi with 16.0 votes
3:  Naga with 19.0 votes
4:  Charcoal Chicken with 25.0 votes
5:  Mangalorean with 32.0 votes

In [3]:
foodToRating = {}
for ind in df.index: 
    if(math.isnan(df.rate[ind])) :
        continue;
    else :
        foodTypes = df.food[ind].split(", ")
        for food in foodTypes :
            if food in foodToRating :
                foodToRating[food] += df.rate[ind]
            else :
                foodToRating[food] = df.rate[ind]
            
ratingToFood = dict([(value, key) for key, value in foodToRating.items()]) 
sortDict = sorted(ratingToFood, reverse=True)
print("The top 5 resturant types by user rating are:\n")
print("1: ", ratingToFood[sortDict[0]] + " with a cumulitive rating of " + str(round(sortDict[0])))
print("2: ", ratingToFood[sortDict[1]] + " with a cumulitive rating of " + str(round(sortDict[1])))
print("3: ", ratingToFood[sortDict[2]] + " with a cumulitive rating of " + str(round(sortDict[2])))
print("4: ", ratingToFood[sortDict[3]] + " with a cumulitive rating of " + str(round(sortDict[3])))
print("5: ", ratingToFood[sortDict[4]] + " with a cumulitive rating of " + str(round(sortDict[4])))
print("\n\n")

sortDict = sorted(ratingToFood)
print("The worst 5 resturant types by user rating are:\n")
print("1: ", ratingToFood[sortDict[0]] + " with a cumulitive rating of " + str(round(sortDict[0])))
print("2: ", ratingToFood[sortDict[1]] + " with a cumulitive rating of " + str(round(sortDict[1])))
print("3: ", ratingToFood[sortDict[2]] + " with a cumulitive rating of " + str(round(sortDict[2])))
print("4: ", ratingToFood[sortDict[3]] + " with a cumulitive rating of " + str(round(sortDict[3])))
print("5: ", ratingToFood[sortDict[4]] + " with a cumulitive rating of " + str(round(sortDict[4])))

The top 5 resturant types by user rating are:

1:  North Indian with a cumulitive rating of 2667.0
2:  Chinese with a cumulitive rating of 1920.0
3:  Fast Food with a cumulitive rating of 1621.0
4:  South Indian with a cumulitive rating of 790.0
5:  Beverages with a cumulitive rating of 770.0



The worst 5 resturant types by user rating are:

1:  Konkan with a cumulitive rating of 3.0
2:  Bangladeshi with a cumulitive rating of 3.0
3:  Naga with a cumulitive rating of 4.0
4:  Bohri with a cumulitive rating of 4.0
5:  Charcoal Chicken with a cumulitive rating of 4.0

In [16]:
# Most popular resturant = (rating*votes)/(avg_cost*cookTime)
foodToScore = {}
for ind in df.index: 
    score = df.rate[ind]*df.votes[ind]/(df.avg_cost[ind]*df.time[ind])
    if (math.isnan(score)) :
       continue;
    else :
        foodToScore[df.id[ind]] = score

scoreToFood = dict([(value, key) for key, value in foodToScore.items()]) 
sortDict = sorted(scoreToFood, reverse=True)
print("The top 5 resturant types by overall score are:\n")
print("1: ", scoreToFood[sortDict[0]] + " with a score of " + str(round(sortDict[0])))
print("2: ", scoreToFood[sortDict[1]] + " with a score of " + str(round(sortDict[1])))
print("3: ", scoreToFood[sortDict[2]] + " with a score of " + str(round(sortDict[2])))
print("4: ", scoreToFood[sortDict[3]] + " with a score of " + str(round(sortDict[3])))
print("5: ", scoreToFood[sortDict[4]] + " with a score of " + str(round(sortDict[4])))

print("\n\n")
sortDict = sorted(scoreToFood)
print("The worst 5 resturant types by overall score are:\n")
print("1: ", scoreToFood[sortDict[0]] + " with a score of " + str(round(sortDict[0])))
print("2: ", scoreToFood[sortDict[1]] + " with a score of " + str(round(sortDict[1])))
print("3: ", scoreToFood[sortDict[2]] + " with a score of " + str(round(sortDict[2])))
print("4: ", scoreToFood[sortDict[3]] + " with a score of " + str(round(sortDict[3])))
print("5: ", scoreToFood[sortDict[4]] + " with a score of " + str(round(sortDict[4])))

The top 5 resturant types by overall score are:

1:  ID_8117 with a score of 122.0
2:  ID_6511 with a score of 38.0
3:  ID_4606 with a score of 32.0
4:  ID_635 with a score of 30.0
5:  ID_4202 with a score of 29.0



The worst 5 resturant types by overall score are:

1:  ID_36 with a score of 0.0
2:  ID_8357 with a score of 0.0
3:  ID_699 with a score of 0.0
4:  ID_6102 with a score of 0.0
5:  ID_7322 with a score of 0.0

In [20]:
# Most bang for your buck = (min/avg*time)
foodToScore = {}
for ind in df.index: 
    score = (df.avg_cost[ind]*df.time[ind])
    if (math.isnan(score)) :
       continue;
    else :
        foodToScore[df.id[ind]] = score

scoreToFood = dict([(value, key) for key, value in foodToScore.items()]) 
sortDict = sorted(scoreToFood, reverse=True)
print("The worst 5 resturants for food and cost are:\n")
print("1: ", scoreToFood[sortDict[0]] + " with a score of " + str(round(sortDict[0])))
print("2: ", scoreToFood[sortDict[1]] + " with a score of " + str(round(sortDict[1])))
print("3: ", scoreToFood[sortDict[2]] + " with a score of " + str(round(sortDict[2])))
print("4: ", scoreToFood[sortDict[3]] + " with a score of " + str(round(sortDict[3])))
print("5: ", scoreToFood[sortDict[4]] + " with a score of " + str(round(sortDict[4])))

print("\n\n")
sortDict = sorted(scoreToFood)
print("The top 5 resturants for food and cost are:\n")
print("1: ", scoreToFood[sortDict[0]] + " with a score of " + str(round(sortDict[0])))
print("2: ", scoreToFood[sortDict[1]] + " with a score of " + str(round(sortDict[1])))
print("3: ", scoreToFood[sortDict[2]] + " with a score of " + str(round(sortDict[2])))
print("4: ", scoreToFood[sortDict[3]] + " with a score of " + str(round(sortDict[3])))
print("5: ", scoreToFood[sortDict[4]] + " with a score of " + str(round(sortDict[4])))

The worst 5 resturants for food and cost are:

1:  ID_8403 with a score of 6750.0
2:  ID_5879 with a score of 5850.0
3:  ID_3192 with a score of 4275.0
4:  ID_2521 with a score of 3900.0
5:  ID_9 with a score of 3600.0



The top 5 resturants for food and cost are:

1:  ID_2545 with a score of 45.0
2:  ID_3209 with a score of 100.0
3:  ID_5474 with a score of 150.0
4:  ID_3670 with a score of 200.0
5:  ID_1517 with a score of 225.0